apiVersion: v1
kind: Namespace
metadata:
  name: wordpress-ns
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wordpress-ns
  name: wordpress-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-pv 
