apiVersion: v1
kind: Pod
metadata:
  name: nginx-xeon
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-label
    image: nginx
    imagePullPolicy: IfNotPresent 
    ports:
    - name: nginx
      containerPort: 80
  - name: redis
    image: redis 
    imagePullPolicy: IfNotPresent 
    ports:
    - name: redis 
      containerPort: 6379
  nodeSelector:
    CPU: Xeon
